spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
#server:
#  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka